export interface StockPrice {
    sandP52WeekChange: number | null;
    address1: string;
    ask: number | null;
    askSize: number | null;
    averageDailyVolume10Day: number | null;
    averageVolume: number | null;
    averageVolume10days: number | null;
    beta: number | null;
    bid: number | null;
    bidSize: number | null;
    bookValue: number | null;
    city: string;
    country: string;
    currency: string;
    dateShortInterest: number | null;
    dayHigh: number | null;
    dayLow: number | null;
    dividendRate: number | null;
    dividendYield: number | null;
    earningsQuarterlyGrowth: number | null;
    enterpriseToEbitda: number | null;
    enterpriseToRevenue: number | null;
    enterpriseValue: number | null;
    exDividendDate: number | null;
    exchange: string;
    exchangeTimezoneName: string;
    exchangeTimezoneShortName: string;
    fax: string;
    fiftyDayAverage: number | null;
    fiftyTwoWeekHigh: number | null;
    fiftyTwoWeekLow: number | null;
    fiveYearAvgDividendYield: number | null;
    floatShares: number | null;
    forwardEps: number | null;
    forwardPE: number | null;
    fullTimeEmployees: number | null;
    gmtOffSetMilliseconds: string;
    heldPercentInsiders: number | null;
    heldPercentInstitutions: number | null;
    industry: string;
    isEsgPopulated: boolean;
    lastFiscalYearEnd: number | null;
    lastSplitDate: number | null;
    lastSplitFactor: string;
    logo_url: string;
    longBusinessSummary: string;
    longName: string;
    market: string;
    marketCap: number | null;
    maxAge: number | null;
    messageBoardId: string;
    mostRecentQuarter: number | null;
    netIncomeToCommon: number | null;
    nextFiscalYearEnd: number | null;
    open: number | null;
    payoutRatio: number | null;
    pegRatio: number | null;
    phone: string;
    previousClose: number | null;
    priceHint: number | null;
    priceToBook: number | null;
    priceToSalesTrailing12Months: number | null;
    profitMargins: number | null;
    quoteType: string;
    regularMarketDayHigh: number | null;
    regularMarketDayLow: number | null;
    regularMarketOpen: number | null;
    regularMarketPreviousClose: number | null;
    regularMarketPrice: number | null;
    regularMarketVolume: number | null;
    sector: string;
    sharesOutstanding: number | null;
    sharesPercentSharesOut: number | null;
    sharesShort: number | null;
    sharesShortPreviousMonthDate: number | null;
    sharesShortPriorMonth: number | null;
    shortName: string;
    shortPercentOfFloat: number | null;
    shortRatio: number | null;
    state: string;
    symbol: string;
    tradeable: boolean;
    trailingAnnualDividendRate: number | null;
    trailingAnnualDividendYield: number | null;
    trailingEps: number | null;
    trailingPE: number | null;
    twoHundredDayAverage: number | null;
    volume: number | null;
    website: string;
    zip: string;
    dateUpdated: string;
    tickChangePositive: boolean | null;
    previousCloseChange: string | null;
    viewCurrency:string | null;
}